Repository cancook/momokji-frontend, pull requests merged in 2023-06, with the labels that each got.

#27 feat: 메인페이지 생성
  .storybook/preview.js
  apis/axios.ts
  apis/youtube.ts
  components/Carousel/Banner/BannerCarousel.stories.tsx
  components/Carousel/Banner/BannerCarousel.tsx
  components/Carousel/Card/CardCarousel.stories.tsx
  components/Carousel/Card/CardCarousel.tsx
  components/Carousel/Card/CardCarouselContainer.tsx
  components/FoodContentCard/Body/index.tsx
  components/FoodContentCard/Footer/CreatorProfile.tsx
  components/FoodContentCard/Thumbnail/ContentImage.tsx
  components/FoodContentCard/Thumbnail/TimeStamp.tsx
  components/layout/Header.stories.tsx
  components/layout/Header.tsx
  constants/dummyData/youtube.ts
  constants/index.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/youtube/category-list.ts
  pages/api/youtube/recommended-list.ts
  pages/index.tsx
  public/svg/self_dining_logo.svg
  styles/Global.ts
  types/youtube.ts
  yarn.lock
Labels: ✨feature

#36 chore: theme 변경 및 스토리북 설정 추가
  .storybook/main.js
  .storybook/preview.js
  styles/Global.ts
  styles/theme.ts
Labels: 💄style

#38 feat: 검색 재료 태그(chip) UI 생성
  components/Search/IngredientsTag/index.stories.tsx
  components/Search/IngredientsTag/index.tsx
  public/svg/close-circle.svg
Labels: ✨feature, 💄style

#37 feat: 빈 검색 결과 컴포넌트 생성
  components/Search/EmptySearchResult/index.stories.tsx
  components/Search/EmptySearchResult/index.tsx
  public/gifs/stir-cook.gif
Labels: ✨feature, 💄style

#41 feat: loading component
  components/Loading/index.stories.tsx
  components/Loading/index.tsx
Labels: 💄style

#42 feat: 바뀐 Header 생성
  .storybook/preview.js
  components/Search/NavigationSearchInput/index.stories.tsx
  components/Search/SearchInput/index.stories.tsx
  components/Search/SearchInput/index.tsx
  components/layout/Header.stories.tsx
  components/layout/Header.tsx
  public/svg/cancook_logo.svg
  styles/Global.ts
Labels: ✨feature, 💄style
